### ISSUE TITLE
iOS : Format 'url' property to auto prefix 'http' as in Android

### ISSUE THREAD

**Issue by prashantsaini1** [appcelerator-modules/titanium-web-dialog#1]
Hans, could you please make the 'url' property to auto check for 'http' prefix before any url as it's in Android?

Though it's not necessary that all websites will use 'http', but it will save some users at least as it's a very simple issue but quite hard to track. OR we can show a log message to prefix the url with **_http_** or **_https_** as required.

**Comment by hansemannn** [comment]
Prefixing it with http is not a good solution. It forces the http protocol even if it's https, rmtp or other protocols that can be used in the web-dialog. If the user provides no proper URL, we should just throw an error and let them know.

**Comment by prashantsaini1** [comment]
As discussed, we are now logging a warning message instead of auto-adding the http/https prefixes.
