### ISSUE TITLE
Doesn't work on Android when targetSDKVersion >= 30

### ISSUE THREAD

**Issue by riodiep** [appcelerator-modules/titanium-web-dialog#173]
When my app use targetSDKVersion = 30, ti.webdialog.open(url) doesn't do anything. 

From adb log I noticed it is blocked from opening the browser. Tested on Samsung s21 Ultra with both Chrome and default Samsung Internet are installed.

`11-12 15:01:41.752  1317  4306 I AppsFilter: interaction: PackageSetting{7ed236d com.myapp/10532} -> PackageSetting{7a02cd6 com.android.chrome/10256} BLOCKED

11-12 15:01:41.752 17911 17911 I TiChromeDialog: (main) [173,7119] No browsers available in this device.

11-12 15:01:42.036  1777  1923 D ScanFilter: manu data matches`

**Comment by cmtanko** [comment]
+1 
Yeah same for me. Unable to release anymore for targetSDKversion 30. Any update on this please

**Comment by m1ga** [comment]
can you try
[ti.webdialog-android-2.1.0.zip](https://github.com/appcelerator-modules/titanium-web-dialog/files/7569249/ti.webdialog-android-2.1.0.zip)
I've updated the dependencies to https://developer.android.com/jetpack/androidx/releases/browser#version_140_3 
One change is `Mark PendingIntents as PendingIntent.FLAG_IMMUTABLE for Android 12 compatibility.`

**Comment by m1ga** [comment]
PR https://github.com/appcelerator-modules/titanium-web-dialog/pull/175

**Comment by riodiep** [comment]
Hi Michael

I've tried that version but still didn't work.

Each time I tried to open I got the message

`[INFO]  TiChromeDialog: (main) [22380,754003] No browsers available in this device.`

**Comment by m1ga** [comment]
works fine here: Android 12, Pixel 4, [example app](https://github.com/appcelerator-modules/titanium-web-dialog/blob/master/example/app.js): opens a green chrome window, I'll get the "open" event and when I click the X it goes back to my app.
Is Chrome installed on the device and is it set as "default browser" in the system settings? In my case I had LightningBrowser as a default so it will open that browser. It doesn't support the colored bar or the "close to app". But when I switch back to Chrome it works fine.

**Comment by cmtanko** [comment]
Hey Michael, I am getting the same error
[INFO]  TiChromeDialog: (main) [49107,792263] No browsers available in this device.

Chrome is my default browser, I am on Samsung Galaxy S20, a11.
Did try downloading other browsers just in case, but that didn't work either.

**Comment by m1ga** [comment]
it is going into the else case here
https://github.com/appcelerator-modules/titanium-web-dialog/blob/master/android/src/ti/webdialog/TitaniumWebDialogModule.java#L156-L158
that means it doesn't find any browser on your device here:
https://github.com/appcelerator-modules/titanium-web-dialog/blob/8a1cc9d62dd316c961b2eaf74311539d85336ab8/android/src/ti/webdialog/Utils.java#L50-L51

You are not using the latest SDK so you have to make more adjustments like this https://stackoverflow.com/a/65852079. 
There might be other things prevent your device from getting the browsers. It would be way easier to use the latest Ti SDK 😉

**Comment by riodiep** [comment]
hi Michael

I'm currently using Ti SDK 10.2.0.v20211006123330. Could you please let me know the latest version that you are using?

It's working for me now by adding this permission which allow getting the browsers.

`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

Thank you.

**Comment by cmtanko** [comment]
Even worked for me after adding this in the manifest file
`            <queries>
                <intent>
                    <action android:name="android.intent.action.VIEW" />
                    <data android:scheme="http" />
                </intent>
            </queries>`

Thanks Michael

**Comment by m1ga** [comment]
Thats interesting. The Ti SDK has that query already:
https://github.com/appcelerator/titanium_mobile/blob/590928ef041a3eeb4f44112386c3c0cfe42b949a/android/app/src/main/AndroidManifest.xml#L17-L20
but for https and the module is trying to open a http page for the browser check. I wonder if that makes a difference and if we change that you don't have to do any changes.

@riodiep I was using 10.1.1.GA but since half the discussion was on slack I knew that there was a 9.3.2 involved and thats why I've mentioned the old SDK. For the unreleased 10.2.0 it normally should work with the queries too. I'm not sure if you can use the ALL PACKAGES query: https://support.google.com/googleplay/android-developer/answer/10158779?hl=en

**Comment by m1ga** [comment]
added the `<queries>` part to my PR so it should work right away even without the `QUERY_ALL_PACKAGES`
