### ISSUE TITLE
Android: Url is opened in lowercase mode, case sensitive urls fails

### ISSUE THREAD

**Issue by ottopic** [appcelerator-modules/titanium-web-dialog#2]
I think is bug of this module. On iOS it seems works fine

**Comment by ottopic** [comment]
I think this is the fail:

https://github.com/appcelerator-modules/titanium-web-dialog/blob/b3f3e23c4d03fe66dee3a1f578af4963d9c7b48d/android/src/ti/webdialog/TitaniumWebDialogModule.java#L64

**Comment by prashantsaini1** [comment]
@ottopic Fixed and thanks for this bug!

**Comment by ottopic** [comment]
@prashantsaini1 thank you for the fix.
